# Generated by Django 4.1.1 on 2022-09-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterField(
            model_name='books',
            name='co_autor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='books',
            name='data_devolucao',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='nome_emprestado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='books',
            name='tempo_duracao',
            field=models.TimeField(blank=True),
        ),
    ]
