# Generated by Django 4.1.1 on 2022-09-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
