# Generated by Django 4.1.1 on 2022-09-20 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_books_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2022, 9, 19)),
        ),
    ]
