# Generated by Django 4.1.1 on 2022-09-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='nome_emprestado',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='tempo_duracao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
