# Generated by Django 4.1.1 on 2022-09-20 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_books_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2022, 9, 20)),
        ),
    ]
